pipeline {
    agent {
        label 'docker'
    }
    tools {
        maven 'maven' // Use the name configured in Jenkins
    }

    stages {
        
        stage('checkout') {
            steps {
                git 'https://github.com/SaravanaNani/jenkins-java-project.git'
            }
        }
        stage('code_compile') {
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/adq-java-app/
                mvn compile
                '''                
            }
        }
        stage('code_test') {
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/adq-java-app/
                mvn test
                '''                
            }
        }
        stage('build_package') {
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/adq-java-app/
                mvn package
                '''                
            }
        }
        stage('Rename WAR') {
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/adq-java-app/target/
                mv NETFLIX-1.2.2.war java_app_v1.${BUILD_NUMBER}.war
                '''
            }
        }
        stage('Upload to Artifactory') {
            steps {
                script {
                    def artifactPath = "target/java_app_v1.${BUILD_NUMBER}.war"
                    googleStorageUpload bucket: 'gs://adq-get-java-artifacts-bucket/', 
                                        credentialsId: 'svc-json-key', 
                                        pattern: artifactPath,
                                        sharedPublicly: true
                }
            }
        }

        stage('Confirm_deployment') {
            steps {
                input message: 'Are you sure you want to proceed with the deployment?', ok: 'Yes'
            }
        }

        stage('Getting war from artifactory') {
            steps {
                sh '''
                /google-cloud-sdk/bin/gsutil cp gs://adq-get-java-artifacts-bucket/target/java_app_v1.${BUILD_NUMBER}.war /var/lib/jenkins/workspace/adq-java-app/target/
                ls -al /var/lib/jenkins/workspace/adq-java-app/target/
                '''
            }
        }

    
         stage('Deploy to Tomcat') {
            steps {
                script {
                    def buildNumber = "${BUILD_NUMBER}"
                    deploy adapters: [
                        tomcat9(
                            credentialsId: 'tomcat-id', // Ensure this ID matches the configured credentials in Jenkins
                            path: '',
                            url: 'http://34.70.115.96:8080/'
                        )
                    ],
                    contextPath: "java_app_v1.${buildNumber}",
                    war: '**/*.war'
                }
            }
        } 
    
        
    }
}
